<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Wc3.Model</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="War3Net.Build" Version="6.0.3" />
    <PackageReference Include="War3Net.IO.Mpq" Version="6.0.3" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Wc3.Tests" />
  </ItemGroup>

</Project>
