using System.Buffers.Binary;
using System.Globalization;
using System.Numerics;
using System.Text.RegularExpressions;
using War3Net.Build.Common;
using War3Net.Build.Info;
using Wc3.Model;

namespace Wc3.Commands;

public sealed record GeneratedHeroRepairAssignment(
    string Rawcode,
    int OriginalOwnerId,
    int OwnerId,
    string X,
    string Y);

public sealed record GeneratedHeroRepairResult(
    bool Ok,
    string Message,
    int PlayerSlotsBefore,
    int PlayerSlotsAfter,
    bool ScriptUpdated,
    bool MapInfoUpdated,
    bool HeaderUpdated,
    IReadOnlyList<GeneratedHeroRepairAssignment> Heroes);

/// <summary>
/// Repairs wc3ctl-generated byproduct maps whose preplaced-hero helper block is too
/// narrow for imported "working source" heroes. The current repair targets the
/// generated `wc3ctl_WirePlacedHeroSpells` / `CreateAllUnits` pattern:
/// it makes spell finalization owner-aware, fixes the `udg_Hero2` 1-based slot write,
/// reassigns duplicated finalized heroes onto distinct real player slots, and expands
/// the script + map-info player declarations so those owners exist consistently.
/// </summary>
public static class GeneratedMapRepairCommand
{
    private static readonly Regex FinalizeHeroRegex = new(
        @"WS_FinalizeWorkingSourceHero\([^,]+,\s*hu,\s*'(?<code>[^']{4})'\)",
        RegexOptions.Compiled);

    private static readonly Regex RegisterTriggerRegex = new(
        @"call TriggerRegisterPlayerUnitEvent\((?<trigger>[^,]+),\s*Player\(\d+\),\s*EVENT_PLAYER_UNIT_SPELL_EFFECT,\s*null\)",
        RegexOptions.Compiled);

    private static readonly Regex CreateUnitRegex = new(
        @"set\s+u\s*=\s*CreateUnit\(Player\((?<owner>\d+)\),\s*'(?<code>[^']{4})',\s*(?<x>[-+]?(?:\d+(?:\.\d+)?|\.\d+)),\s*(?<y>[-+]?(?:\d+(?:\.\d+)?|\.\d+)),\s*(?<z>[-+]?(?:\d+(?:\.\d+)?|\.\d+))\)",
        RegexOptions.Compiled);

    private static readonly Regex CreateUnitOwnerRegex = new(
        @"(?<prefix>CreateUnit\(Player\()(?<owner>\d+)(?<suffix>\),\s*'(?<code>[^']{4})')",
        RegexOptions.Compiled);

    private static readonly Regex SetPlayersRegex = new(
        @"call SetPlayers\(\s*\d+\s*\)",
        RegexOptions.Compiled);

    private static readonly Regex DefineStartLocationRegex = new(
        @"call DefineStartLocation\(\s*(?<id>\d+),\s*(?<x>[-+]?(?:\d+(?:\.\d+)?|\.\d+)),\s*(?<y>[-+]?(?:\d+(?:\.\d+)?|\.\d+))\s*\)",
        RegexOptions.Compiled);

    private static readonly Regex TeamLineRegex = new(
        @"call SetPlayerTeam\(\s*Player\((?<id>\d+)\),\s*(?<team>\d+)\s*\)",
        RegexOptions.Compiled);

    private sealed record HeroPlacement(string Rawcode, int OriginalOwnerId, string X, string Y);

    public static GeneratedHeroRepairResult RepairGeneratedHeroes(MapDocument doc)
    {
        ArgumentNullException.ThrowIfNull(doc);

        var scriptEntry = doc.GetFile("war3map.j") ?? doc.GetFile(@"scripts\war3map.j");
        if (scriptEntry?.FileName is null)
            return Fail("map contains no war3map.j script");

        string source = FileEditCommand.ReadText(doc, scriptEntry.FileName);
        var functions = JassFunctionIndex.Parse(source).ToDictionary(f => f.Name, StringComparer.Ordinal);
        if (!functions.TryGetValue("wc3ctl_WirePlacedHeroSpells", out var wireFn)
            || !functions.TryGetValue("CreateAllUnits", out var createFn)
            || !functions.TryGetValue("InitCustomPlayerSlots", out var slotsFn)
            || !functions.TryGetValue("InitCustomTeams", out var teamsFn)
            || !functions.TryGetValue("config", out var configFn))
            return Fail("map does not contain the generated wc3ctl preplaced-hero helper block");

        var lineStarts = ScriptCommand.ComputeLineStarts(source);
        string wireText = ScriptCommand.SliceFunction(source, lineStarts, wireFn.StartLine, wireFn.EndLine);
        string createText = ScriptCommand.SliceFunction(source, lineStarts, createFn.StartLine, createFn.EndLine);
        string configText = ScriptCommand.SliceFunction(source, lineStarts, configFn.StartLine, configFn.EndLine);

        var heroCodes = FinalizeHeroRegex.Matches(wireText)
            .Select(m => m.Groups["code"].Value)
            .Distinct(StringComparer.Ordinal)
            .ToList();
        if (heroCodes.Count == 0)
            return Fail("generated hero helper contains no finalized hero rawcodes");
        if (heroCodes.Count > 24)
            return Fail($"generated hero helper wants {heroCodes.Count} hero owners, only 24 regular player slots exist");

        var triggerNames = RegisterTriggerRegex.Matches(wireText)
            .Select(m => m.Groups["trigger"].Value.Trim())
            .Distinct(StringComparer.Ordinal)
            .ToList();
        if (triggerNames.Count == 0)
            return Fail("generated hero helper contains no spell-effect trigger registrations");

        var placements = CreateUnitRegex.Matches(createText)
            .Select(m => new HeroPlacement(
                m.Groups["code"].Value,
                int.Parse(m.Groups["owner"].Value, CultureInfo.InvariantCulture),
                m.Groups["x"].Value,
                m.Groups["y"].Value))
            .Where(p => heroCodes.Contains(p.Rawcode, StringComparer.Ordinal))
            .ToList();

        var assignments = AssignOwners(heroCodes, placements);
        if (assignments.Count != heroCodes.Count)
            return Fail("could not map every finalized hero rawcode to a CreateUnit placement");

        int declaredPlayersBefore = DeclaredPlayerCount(doc, configText);
        int playerSlotsAfter = Math.Max(declaredPlayersBefore, assignments.Max(a => a.OwnerId) + 1);

        var controllers = BuildControllerMap(doc, playerSlotsAfter);
        var teams = BuildTeamMap(configText, playerSlotsAfter);
        var startLocations = BuildStartLocations(configText, playerSlotsAfter, assignments);

        string repairedWire = BuildWireFunction(triggerNames, assignments, playerSlotsAfter);
        string repairedCreate = RewriteCreateAllUnits(createText, assignments);
        string repairedSlots = BuildInitCustomPlayerSlots(controllers);
        string repairedTeams = BuildInitCustomTeams(teams);
        string repairedConfig = BuildConfig(configText, playerSlotsAfter, startLocations);

        var replacements = new (JassFunction Fn, string Text)[]
        {
            (configFn, repairedConfig),
            (teamsFn, repairedTeams),
            (createFn, repairedCreate),
            (wireFn, repairedWire),
            (slotsFn, repairedSlots),
        };

        string updatedSource = source;
        foreach (var (fn, text) in replacements.OrderByDescending(r => r.Fn.StartLine))
            updatedSource = ScriptCommand.ReplaceFunction(updatedSource, lineStarts, fn, text);
        FileEditCommand.WriteText(doc, scriptEntry.FileName, updatedSource);

        bool mapInfoUpdated = UpdateMapInfo(doc, assignments, controllers, teams, playerSlotsAfter);
        bool headerUpdated = TryWriteHeaderMaxPlayers(doc.PreArchiveData, playerSlotsAfter);

        return new GeneratedHeroRepairResult(
            Ok: true,
            Message: $"repaired generated hero wiring for {assignments.Count} finalized hero slot(s)",
            PlayerSlotsBefore: declaredPlayersBefore,
            PlayerSlotsAfter: playerSlotsAfter,
            ScriptUpdated: true,
            MapInfoUpdated: mapInfoUpdated,
            HeaderUpdated: headerUpdated,
            Heroes: assignments);
    }

    private static GeneratedHeroRepairResult Fail(string message) =>
        new(false, message, 0, 0, false, false, false, Array.Empty<GeneratedHeroRepairAssignment>());

    private static List<GeneratedHeroRepairAssignment> AssignOwners(
        IReadOnlyList<string> heroCodes,
        IReadOnlyList<HeroPlacement> placements)
    {
        var byCode = placements
            .GroupBy(p => p.Rawcode, StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => new Queue<HeroPlacement>(g), StringComparer.Ordinal);
        var used = new HashSet<int>();
        var assigned = new List<GeneratedHeroRepairAssignment>();

        foreach (var code in heroCodes)
        {
            if (!byCode.TryGetValue(code, out var queue) || queue.Count == 0)
                return new List<GeneratedHeroRepairAssignment>();

            var placement = queue.Dequeue();
            int owner = placement.OriginalOwnerId;
            if (owner is < 0 or >= 24 || !used.Add(owner))
            {
                owner = Enumerable.Range(0, 24).FirstOrDefault(i => !used.Contains(i));
                if (used.Contains(owner))
                    return new List<GeneratedHeroRepairAssignment>();
                used.Add(owner);
            }

            assigned.Add(new GeneratedHeroRepairAssignment(
                placement.Rawcode,
                placement.OriginalOwnerId,
                owner,
                placement.X,
                placement.Y));
        }

        return assigned;
    }

    private static int DeclaredPlayerCount(MapDocument doc, string configText)
    {
        if (doc.GetFile(MapInfoCommand.FileName)?.Model is MapInfo info && info.Players.Count > 0)
            return info.Players.Max(p => p.Id) + 1;

        var match = SetPlayersRegex.Match(configText);
        return match.Success
            ? int.Parse(Regex.Match(match.Value, @"\d+").Value, CultureInfo.InvariantCulture)
            : 1;
    }

    private static IReadOnlyDictionary<int, string> BuildControllerMap(MapDocument doc, int playerSlotsAfter)
    {
        var map = new Dictionary<int, string>();
        if (doc.GetFile(MapInfoCommand.FileName)?.Model is MapInfo info)
        {
            foreach (var player in info.Players)
                map[player.Id] = player.Controller == PlayerController.Computer
                    ? "MAP_CONTROL_COMPUTER"
                    : "MAP_CONTROL_USER";
        }

        for (int id = 0; id < playerSlotsAfter; id++)
            map.TryAdd(id, id == 0 ? "MAP_CONTROL_USER" : "MAP_CONTROL_COMPUTER");
        return map;
    }

    private static IReadOnlyDictionary<int, int> BuildTeamMap(string teamsText, int playerSlotsAfter)
    {
        var teams = TeamLineRegex.Matches(teamsText)
            .ToDictionary(
                m => int.Parse(m.Groups["id"].Value, CultureInfo.InvariantCulture),
                m => int.Parse(m.Groups["team"].Value, CultureInfo.InvariantCulture));

        for (int id = 0; id < playerSlotsAfter; id++)
            teams.TryAdd(id, 0);
        return teams;
    }

    private static IReadOnlyDictionary<int, (string X, string Y)> BuildStartLocations(
        string configText,
        int playerSlotsAfter,
        IReadOnlyList<GeneratedHeroRepairAssignment> assignments)
    {
        var starts = DefineStartLocationRegex.Matches(configText)
            .ToDictionary(
                m => int.Parse(m.Groups["id"].Value, CultureInfo.InvariantCulture),
                m => (m.Groups["x"].Value, m.Groups["y"].Value));

        foreach (var hero in assignments)
            starts[hero.OwnerId] = (hero.X, hero.Y);

        for (int id = 0; id < playerSlotsAfter; id++)
            starts.TryAdd(id, ("0.0", "0.0"));
        return starts;
    }

    private static string BuildWireFunction(
        IReadOnlyList<string> triggerNames,
        IReadOnlyList<GeneratedHeroRepairAssignment> heroes,
        int playerSlotsAfter)
    {
        var lines = new List<string>
        {
            "function wc3ctl_WirePlacedHeroSpells takes nothing returns nothing",
            "    local group g = CreateGroup()",
            "    local unit hu",
            "    local boolean ok",
            "    local integer i = 0",
            "    loop",
            $"        exitwhen i >= {playerSlotsAfter}",
        };

        foreach (var trigger in triggerNames)
            lines.Add($"        call TriggerRegisterPlayerUnitEvent({trigger}, Player(i), EVENT_PLAYER_UNIT_SPELL_EFFECT, null)");
        lines.Add("        call GroupEnumUnitsOfPlayer(g, Player(i), null)");
        lines.Add("        loop");
        lines.Add("            set hu = FirstOfGroup(g)");
        lines.Add("            exitwhen hu == null");
        lines.Add("            call GroupRemoveUnit(g, hu)");
        foreach (var hero in heroes)
        {
            lines.Add($"            if GetUnitTypeId(hu) == '{hero.Rawcode}' then");
            lines.Add($"                set ok = WS_FinalizeWorkingSourceHero(GetOwningPlayer(hu), hu, '{hero.Rawcode}')");
            lines.Add("            endif");
        }
        lines.Add("        endloop");
        lines.Add("        set i = i + 1");
        lines.Add("    endloop");
        lines.Add("    call DestroyGroup(g)");
        lines.Add("    set g = null");
        lines.Add("    set hu = null");
        lines.Add("    call DestroyTimer(GetExpiredTimer())");
        lines.Add("endfunction");
        return string.Join("\n", lines);
    }

    private static string RewriteCreateAllUnits(
        string createText,
        IReadOnlyList<GeneratedHeroRepairAssignment> assignments)
    {
        var owners = assignments.ToDictionary(a => a.Rawcode, a => a.OwnerId, StringComparer.Ordinal);
        string updated = CreateUnitOwnerRegex.Replace(createText, m =>
        {
            string code = m.Groups["code"].Value;
            return owners.TryGetValue(code, out var owner)
                ? m.Groups["prefix"].Value + owner.ToString(CultureInfo.InvariantCulture) + m.Groups["suffix"].Value
                : m.Value;
        });

        return updated.Replace(
            "udg_Hero2[GetPlayerId(GetOwningPlayer(u))]",
            "udg_Hero2[1 + GetPlayerId(GetOwningPlayer(u))]",
            StringComparison.Ordinal);
    }

    private static string BuildInitCustomPlayerSlots(IReadOnlyDictionary<int, string> controllers)
    {
        var lines = new List<string>
        {
            "function InitCustomPlayerSlots takes nothing returns nothing",
        };

        foreach (var playerId in controllers.Keys.OrderBy(id => id))
        {
            lines.Add($"    call SetPlayerStartLocation( Player({playerId}), {playerId} )");
            lines.Add($"    call SetPlayerColor( Player({playerId}), ConvertPlayerColor({playerId}) )");
            lines.Add($"    call SetPlayerRacePreference( Player({playerId}), RACE_PREF_HUMAN )");
            lines.Add($"    call SetPlayerRaceSelectable( Player({playerId}), true )");
            lines.Add($"    call SetPlayerController( Player({playerId}), {controllers[playerId]} )");
        }

        lines.Add("endfunction");
        return string.Join("\n", lines);
    }

    private static string BuildInitCustomTeams(IReadOnlyDictionary<int, int> teams)
    {
        var lines = new List<string>
        {
            "function InitCustomTeams takes nothing returns nothing",
            "    // Force: Force 1",
        };

        foreach (var playerId in teams.Keys.OrderBy(id => id))
            lines.Add($"    call SetPlayerTeam( Player({playerId}), {teams[playerId]} )");
        lines.Add("endfunction");
        return string.Join("\n", lines);
    }

    private static string BuildConfig(
        string configText,
        int playerSlotsAfter,
        IReadOnlyDictionary<int, (string X, string Y)> startLocations)
    {
        string mapNameLine = FindOrDefault(configText, "call SetMapName(", "    call SetMapName( \"Generated Map\" )");
        string mapDescriptionLine = FindOrDefault(configText, "call SetMapDescription(", "    call SetMapDescription( \"Created with wc3ctl.\" )");
        string teamsLine = FindOrDefault(configText, "call SetTeams(", "    call SetTeams( 1 )");
        string placementLine = FindOrDefault(configText, "call SetGamePlacement(", "    call SetGamePlacement( MAP_PLACEMENT_USE_MAP_SETTINGS )");

        var lines = new List<string>
        {
            "function config takes nothing returns nothing",
            mapNameLine,
            mapDescriptionLine,
            $"    call SetPlayers( {playerSlotsAfter} )",
            teamsLine,
            placementLine,
            string.Empty,
        };

        foreach (var playerId in startLocations.Keys.OrderBy(id => id))
        {
            if (playerId >= playerSlotsAfter)
                continue;
            var (x, y) = startLocations[playerId];
            lines.Add($"    call DefineStartLocation( {playerId}, {x}, {y} )");
        }

        lines.Add(string.Empty);
        lines.Add("    // Player setup");
        lines.Add("    call InitCustomPlayerSlots(  )");
        lines.Add("    call InitCustomTeams(  )");
        lines.Add("endfunction");
        return string.Join("\n", lines);
    }

    private static string FindOrDefault(string source, string token, string fallback)
    {
        var line = source.Replace("\r\n", "\n")
            .Split('\n')
            .FirstOrDefault(l => l.Contains(token, StringComparison.Ordinal));
        return string.IsNullOrWhiteSpace(line) ? fallback : line.TrimEnd('\r');
    }

    private static bool UpdateMapInfo(
        MapDocument doc,
        IReadOnlyList<GeneratedHeroRepairAssignment> assignments,
        IReadOnlyDictionary<int, string> controllers,
        IReadOnlyDictionary<int, int> teams,
        int playerSlotsAfter)
    {
        if (doc.GetFile(MapInfoCommand.FileName)?.Model is not MapInfo info)
            return false;

        var byId = info.Players.ToDictionary(p => p.Id);
        for (int id = 0; id < playerSlotsAfter; id++)
        {
            if (!byId.ContainsKey(id))
            {
                var player = new PlayerData
                {
                    Id = id,
                    Name = PlayerColors.DisplayName(id),
                    Controller = controllers[id] == "MAP_CONTROL_COMPUTER"
                        ? PlayerController.Computer
                        : PlayerController.User,
                    Race = PlayerRace.Human,
                    Flags = 0,
                    StartPosition = default,
                    AllyLowPriorityFlags = new Bitmask32(0),
                    AllyHighPriorityFlags = new Bitmask32(0),
                    EnemyLowPriorityFlags = new Bitmask32(0),
                    EnemyHighPriorityFlags = new Bitmask32(0),
                };
                info.Players.Add(player);
                byId[id] = player;
            }
        }

        foreach (var hero in assignments)
        {
            if (!byId.TryGetValue(hero.OwnerId, out var player))
                continue;
            player.StartPosition = new Vector2(
                float.Parse(hero.X, CultureInfo.InvariantCulture),
                float.Parse(hero.Y, CultureInfo.InvariantCulture));
        }

        if (info.Forces.Count == 0)
        {
            info.Forces.Add(new ForceData
            {
                Name = "Force 1",
                Flags = ForceFlags.Allied | ForceFlags.AlliedVictory,
                Players = new Bitmask32(0),
            });
        }

        foreach (var force in info.Forces)
            force.Players ??= new Bitmask32(0);

        for (int id = 0; id < playerSlotsAfter; id++)
            info.Forces[0].Players![id] = true;

        foreach (var force in info.Forces.Skip(1))
            for (int id = 0; id < playerSlotsAfter; id++)
                force.Players![id] = false;

        var entry = doc.AddOrReplaceRawFile(MapInfoCommand.FileName, MapInfoCommand.Serialize(info));
        entry.Model = info;
        return true;
    }

    private static bool TryWriteHeaderMaxPlayers(byte[] preArchiveData, int playerSlotsAfter)
    {
        if (preArchiveData.Length < 16)
            return false;
        if (preArchiveData[0] != (byte)'H'
            || preArchiveData[1] != (byte)'M'
            || preArchiveData[2] != (byte)'3'
            || preArchiveData[3] != (byte)'W')
            return false;

        int nameTerminator = Array.IndexOf(preArchiveData, (byte)0, 8);
        if (nameTerminator < 0 || nameTerminator + 9 > preArchiveData.Length)
            return false;

        BinaryPrimitives.WriteUInt32LittleEndian(
            preArchiveData.AsSpan(nameTerminator + 5, 4),
            (uint)Math.Max(playerSlotsAfter, 1));
        return true;
    }
}
