using Wc3.Model;

namespace Wc3.Commands;

public static class RoundtripCommand
{
    // MPQ bookkeeping files regenerated by MpqArchiveBuilder on save. They are
    // archive metadata, not map data, so they may legitimately differ on
    // round-trip and are excluded from the fidelity verdict (same rule as
    // tests/Wc3.Tests/RoundtripTests.cs).
    private static readonly HashSet<string> MpqSpecialFiles = new(StringComparer.OrdinalIgnoreCase)
    {
        "(listfile)", "(attributes)", "(signature)",
    };

    public static RoundtripResult Execute(MapDocument doc)
    {
        var rebuilt = MapDocument.Load(doc.SaveToBytes());
        var mismatches = new List<string>();
        if (!doc.PreArchiveData.SequenceEqual(rebuilt.PreArchiveData))
            mismatches.Add("(pre-archive header)");
        var diff = DiffCommand.Execute(doc, rebuilt);
        mismatches.AddRange(diff.Entries
            .Where(e => !MpqSpecialFiles.Contains(e.Name))
            .Select(e => $"{e.Name}:{e.Change}"));
        return new RoundtripResult(mismatches.Count == 0, mismatches);
    }
}
