<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Wc3.Modeling</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="War3Net.Drawing.Blp" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Wc3.Tests" />
  </ItemGroup>

</Project>
