// tests/Wc3.Tests/RoundtripTests.cs
using Wc3.Model;

namespace Wc3.Tests;

public class RoundtripTests
{
    // MPQ bookkeeping files regenerated by MpqArchiveBuilder on save. They are
    // archive metadata, not map data, so they may legitimately differ on
    // round-trip and are excluded from fidelity comparisons.
    private static readonly HashSet<string> MpqSpecialFiles = new(StringComparer.OrdinalIgnoreCase)
    {
        "(listfile)", "(attributes)", "(signature)",
    };

    private static byte[] Sample() => SyntheticMap.Build(new Dictionary<string, byte[]>
    {
        ["war3map.w3i"] = Enumerable.Range(0, 300).Select(i => (byte)i).ToArray(),
        ["war3map.j"]   = System.Text.Encoding.UTF8.GetBytes("function main takes nothing returns nothing\nendfunction\n"),
        ["mystery.bin"] = new byte[] { 42, 0, 255, 7 },
    });

    private static Dictionary<string, byte[]> ContentFilesByName(MapDocument doc) =>
        doc.Files.Where(f => f.FileName != null && !MpqSpecialFiles.Contains(f.FileName!))
                 .ToDictionary(f => f.FileName!, f => f.RawBytes);

    [Fact]
    public void No_edit_roundtrip_preserves_every_file_and_header()
    {
        var original = MapDocument.Load(Sample());
        var rebuilt = MapDocument.Load(original.SaveToBytes());

        Assert.Equal(original.PreArchiveData, rebuilt.PreArchiveData);

        var origByName = ContentFilesByName(original);
        var newByName = ContentFilesByName(rebuilt);

        Assert.Equal(origByName.Keys.OrderBy(k => k), newByName.Keys.OrderBy(k => k));
        foreach (var (name, bytes) in origByName)
            Assert.Equal(bytes, newByName[name]);
    }

    [Fact]
    [Trait("Category", "Corpus")]
    public void Real_map_roundtrips_every_file()
    {
        const string path = @"C:\Users\GodMephisto\Downloads\ggg_en_1.11r_slk.w3x";
        if (!File.Exists(path)) return;

        var original = MapDocument.Load(path);
        var rebuilt = MapDocument.Load(original.SaveToBytes());

        var orig = ContentFilesByName(original);
        var round = ContentFilesByName(rebuilt);
        foreach (var (name, bytes) in orig)
            Assert.True(round.ContainsKey(name) && round[name].SequenceEqual(bytes), $"mismatch: {name}");
    }
}
